# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller

  joint_trajectory_controller:
    type: FollowJointTrajectory
    joints:
      - ada_joint_1
      - ada_joint_2
      - ada_joint_3
      - ada_joint_4
      - ada_joint_5
      - ada_joint_6
      - ada_joint_7
    action_ns: follow_joint_trajectory
    default: true